version: '3.8'

services:
  example-frontend:
    container_name: frontend
    build: ./example-frontend
    ports:
      - 5000:5000
    networks:
      - hello-network

  example-backend:
    container_name: backend
    build: ./example-backend
    ports:
      - 8080:8080
    networks:
      - hello-network

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    networks:
      - hello-network

  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=db
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - hello-network

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - hello-network

networks:
  hello-network:

volumes:
  database:

