version: '3.8'

services:
    example-frontend:
        container_name: frontend
        build: ./example-frontend
        ports:
            - 5000:5000

    example-backend:
        container_name: backend
        build: ./example-backend
        ports:
            - 8080:8080
        environment:
            - REDIS_HOST=redis

    redis-cache:
      container_name: cache
      image: redis:latest
      restart: unless-stopped

