version: "3.8"

services:
  example-frontend:
    container_name: frontend
    build: ./example-frontend
#    ports:
#      - 5000:5000

  example-backend:
    container_name: backend
    build: ./example-backend
#    ports:
#      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=example
      - POSTGRESS_DATABASE=db
    depends_on:
      - redis-cache
      - db

  redis-cache:
    image: redis
    container_name: redis

  db:
    image: postgres:13.2-alpine
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=db
    volumes:
      - ./data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
