version: '3.8'

services:
    example-frontend:
        build: ./frontend
        ports:
            - 5000:5000
        container_name: frontend

    example-backend:
        build: ./backend
        ports:
            - 8080:8080
        container_name: backend
